// AUTO-GENERATED by scripts/build-site-data.mjs — do not edit.
// Task 44-30: build-time snapshot of registered GAD projects from gad-config.toml.

export interface RegisteredProject {
  id: string;
  kind: "planning" | "evals" | "both";
  path: string;
}

export const REGISTERED_PROJECTS: RegisteredProject[] = [
  {
    "id": "get-anything-done",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\vendor\\get-anything-done"
  },
  {
    "id": "grime-time",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\vendor\\grime-time-site"
  },
  {
    "id": "repub-builder",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\vendor\\repub-builder"
  },
  {
    "id": "mb-cli-framework",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\vendor\\mb-cli-framework"
  },
  {
    "id": "magicborn",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\projects\\magicborn"
  },
  {
    "id": "global",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio"
  },
  {
    "id": "app-forge",
    "kind": "both",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\apps\\forge"
  },
  {
    "id": "project-editor",
    "kind": "both",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\projects\\project-editor"
  },
  {
    "id": "claw-cli",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\vendor\\claw-code"
  },
  {
    "id": "llm-from-scratch",
    "kind": "planning",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\projects\\llm-from-scratch"
  },
  {
    "id": "portfolio-legacy",
    "kind": "evals",
    "path": "C:\\Users\\benja\\Documents\\custom_portfolio\\evals"
  }
];

export const DEFAULT_PROJECT_ID: string = "get-anything-done";
