#!/usr/bin/env node
/**
 * build-stamp.mjs — emit lib/build-stamp.generated.cjs with git SHA + src hash.
 *
 * bun build --compile flattens the repo into a single exe, so `execSync('git
 * rev-parse HEAD')` at runtime resolves against the user's cwd (wrong repo)
 * or a virtual bundle path (no repo at all). This script freezes the identity
 * at build time: version, commit, branch, commit timestamp, src hash.
 *
 * The src hash is a deterministic SHA-256 over the sorted list of
 * {path, size, mtime-as-content-hash} triples for bin/, lib/, scripts/, and
 * package.json — everything that can meaningfully affect behavior. It's the
 * staleness primitive the pre-commit hook (task 66-04) uses to decide whether
 * a rebuild is required.
 *
 * Loaded by lib/framework-version.cjs as the source of truth when present;
 * runtime git query is the fallback for dev (unbundled) contexts.
 */

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const STAMP_PATH = join(ROOT, 'lib', 'build-stamp.generated.cjs');

const HASH_TARGETS = ['bin', 'lib', 'scripts', 'package.json'];
const HASH_SKIP = new Set(['node_modules', 'dist', '.git', 'tmp', '.gad-try']);
const HASH_SKIP_FILE_PATTERNS = [/\.generated\.(js|cjs|mjs|ts)$/, /\._manifest\.cjs$/, /^_manifest\.cjs$/];

function safeExec(cmd, args) {
  try {
    return execFileSync(cmd, args, { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString('utf8')
      .trim();
  } catch {
    return null;
  }
}

function shouldSkipFile(name) {
  return HASH_SKIP_FILE_PATTERNS.some((re) => re.test(name));
}

function walkFiles(target, absBase, out) {
  let stat;
  try { stat = statSync(absBase); } catch { return; }
  if (stat.isFile()) {
    if (shouldSkipFile(target.split(/[\\/]/).pop() || '')) return;
    out.push(target);
    return;
  }
  if (!stat.isDirectory()) return;
  for (const entry of readdirSync(absBase)) {
    if (HASH_SKIP.has(entry)) continue;
    if (entry.startsWith('.')) continue;
    walkFiles(`${target}/${entry}`, join(absBase, entry), out);
  }
}

function computeSrcHash() {
  const paths = [];
  for (const target of HASH_TARGETS) {
    walkFiles(target, join(ROOT, target), paths);
  }
  paths.sort();
  const hash = createHash('sha256');
  for (const rel of paths) {
    const content = readFileSync(join(ROOT, rel));
    hash.update(rel);
    hash.update('\0');
    hash.update(content);
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 16);
}

function main() {
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  const commit = safeExec('git', ['rev-parse', '--short', 'HEAD']);
  const branch = safeExec('git', ['rev-parse', '--abbrev-ref', 'HEAD']);
  const commitTs = safeExec('git', ['log', '-1', '--format=%cI']);
  const srcHash = computeSrcHash();
  const builtAt = new Date().toISOString();

  const stamp = {
    version: pkg.version,
    methodology_version: pkg.gadMethodologyVersion || null,
    commit,
    branch,
    commit_ts: commitTs,
    src_hash: srcHash,
    built_at: builtAt,
  };

  const body = [
    "'use strict';",
    '/**',
    ' * GENERATED by scripts/build-stamp.mjs. Do not edit by hand.',
    ' *',
    ' * Frozen at build time so the bundled exe reports correct identity',
    ' * without shelling out to git at runtime (task 66-06).',
    ' */',
    '',
    `module.exports = ${JSON.stringify(stamp, null, 2)};`,
    '',
  ].join('\n');

  writeFileSync(STAMP_PATH, body, 'utf8');
  console.log(`Wrote build stamp: ${stamp.version}+${stamp.commit} src=${stamp.src_hash} → ${relative(ROOT, STAMP_PATH)}`);
}

main();
