/**
 * Task 42.2-43: planning-graph HTTP surface for the GAD landing site.
 *
 *   GET /api/planning/graph                 → full envelope
 *   GET /api/planning/graph?related=<id>    → 1-hop neighbourhood
 *   GET /api/planning/graph?related=<id>&radius=2
 *   GET /api/planning/graph?search=<query>  → token-indexed lookup
 *   GET /api/planning/graph?node=<id>       → single node + neighbourhood
 *
 * Optional filters (apply only to neighbourhood queries):
 *   edgeTypes=cites,depends_on
 *   nodeTypes=phase,task,decision
 *   limit=50
 *
 * The route is cached at the module level via the reader's
 * Map-backed cache; subsequent requests pay only the JSON.stringify
 * cost. The underlying file is regenerated by build-site-data.mjs on
 * every prebuild so production never serves a stale tree.
 */

import {
  getPlanningGraph,
  getPlanningNode,
  getNeighborhood,
  searchPlanningGraph,
} from "@/lib/planning-graph";

export const runtime = "nodejs";
// Read the file at request time so dev (where build-site-data may run
// after the server boots) sees fresh data without a restart.
export const dynamic = "force-dynamic";

function parseList(value: string | null): string[] | undefined {
  if (!value) return undefined;
  const arr = value
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  return arr.length > 0 ? arr : undefined;
}

function clampInt(
  value: string | null,
  fallback: number,
  min: number,
  max: number,
): number {
  if (!value) return fallback;
  const n = Number.parseInt(value, 10);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}

export async function GET(request: Request): Promise<Response> {
  const url = new URL(request.url);
  const search = url.searchParams.get("search");
  const related = url.searchParams.get("related");
  const node = url.searchParams.get("node");

  if (search) {
    const limit = clampInt(url.searchParams.get("limit"), 25, 1, 200);
    const hits = searchPlanningGraph(search, limit);
    return Response.json({
      query: search,
      count: hits.length,
      hits,
    });
  }

  if (related || node) {
    const id = (related ?? node)!;
    const radius = clampInt(url.searchParams.get("radius"), 1, 1, 4);
    const limit = clampInt(url.searchParams.get("limit"), 200, 1, 1000);
    const edgeTypes = parseList(url.searchParams.get("edgeTypes"));
    const nodeTypes = parseList(url.searchParams.get("nodeTypes"));
    const result = getNeighborhood(id, { radius, limit, edgeTypes, nodeTypes });
    if (!result.origin) {
      return Response.json(
        { error: `unknown node id: ${id}`, origin: null, nodes: [], edges: [] },
        { status: 404 },
      );
    }
    return Response.json({
      origin: result.origin,
      radius,
      nodeCount: result.nodes.length,
      edgeCount: result.edges.length,
      nodes: result.nodes,
      edges: result.edges,
    });
  }

  // Single-node short-circuit (returns just the node, no traversal).
  const onlyNode = url.searchParams.get("only");
  if (onlyNode) {
    const n = getPlanningNode(onlyNode);
    if (!n) {
      return Response.json({ error: `unknown node id: ${onlyNode}` }, { status: 404 });
    }
    return Response.json(n);
  }

  return Response.json(getPlanningGraph());
}
